version: '3.1'
services:
  stats-server:
    build: ewm-stat-service/server
    image: ewm-stat-server
    container_name: ewm-stat-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - EWM_DATASOURSE_URL=jdbc:postgresql://ewm-stat-db:5432

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=stats

  ewm-service:
    build: ewm-main-service
    image: ewm-main-server
    container_name: ewm-main-server
    depends_on:
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - EWM_DATASOURSE_URL=jdbc:postgresql://ewm-main-db:5432
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=stats