CREATE TABLE IF NOT EXISTS statistics
(
    hit_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    application VARCHAR(255)                            NOT NULL,
    uri         VARCHAR(512)                            NOT NULL,
    ip          VARCHAR(255)                            NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_statistics PRIMARY KEY (hit_id)
);